In [1]:
import gym
import numpy as np
import random
import time

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size=env.action_space.n #columns -> possible actions
state_space_size=env.observation_space.n #rows

In [4]:
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
n_episodes=2000
max_steps_per_episode=100

lr=0.1
discount_rate=0.99 #refer to Q-Learning equation -> lr*(R_n+1 + gamma*max(Q^(s',a'))) + (1-lr)*Q^(s,a)

exploration_rate=1 #epsilon explitation relation
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [13]:
rewards_all_episodes=[]

#Q-learning algo

for episode in range(n_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        
        exploration_threshold= random.uniform(0,1)
        if(exploration_threshold>exploration_rate):
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        print(env.step(action))
        
        q_table[state, action]= q_table[state, action]*(1-lr) + lr*(
            reward + discount_rate*np.argmax(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode+=reward
        
        if(done==True):
            break
    
    #exploration rate decay for each episode after finding/not-finding the end-goal in n steps of an episode
    exploration_rate = min_exploration_rate + (
            max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    print(exploration_rate)
        
    rewards_all_episodes.append(rewards_current_episode)
    
reward_per_thousand_episodes= np.split(np.array(rewards_all_episodes),n_episodes/100)
print("reward per thousand episodes: ",reward_per_thousand_episodes)
count=100
print("****Average reward per thousand episodes***** \n")
for r in reward_per_thousand_episodes:
    print(count,": ",str(sum(r/1000)))
    count+=100

#updated q table
print("\n***Q-Table***\n")
print(q_table)
    

(5, 0.0, True, {'prob': 0.3333333333333333})
(5, 0, True, {'prob': 1.0})
1.0
(0, 0.0, False, {'prob': 0.3333333333333333})
(2, 0.0, False, {'prob': 0.3333333333333333})
(7, 0.0, True, {'prob': 0.3333333333333333})
(7, 0, True, {'prob': 1.0})
0.9990104948350412
(1, 0.0, False, {'prob': 0.3333333333333333})
(5, 0, True, {'prob': 1.0})
0.9980219786806598
(1, 0.0, False, {'prob': 0.3333333333333333})
(1, 0.0, False, {'prob': 0.3333333333333333})
(1, 0.0, False, {'prob': 0.3333333333333333})
(1, 0.0, False, {'prob': 0.3333333333333333})
(1, 0.0, False, {'prob': 0.3333333333333333})
(2, 0.0, False, {'prob': 0.3333333333333333})
(2, 0.0, False, {'prob': 0.3333333333333333})
(2, 0.0, False, {'prob': 0.3333333333333333})
(10, 0.0, False, {'prob': 0.3333333333333333})
(5, 0.0, True, {'prob': 0.3333333333333333})
(5, 0, True, {'prob': 1.0})
0.9970344505483393
(4, 0.0, False, {'prob': 0.3333333333333333})
(4, 0.0, False, {'prob': 0.3333333333333333})
(0, 0.0, False, {'prob': 0.3333333333333333})
(

In [14]:
from IPython.display import clear_output

In [ ]:
for episode in range(3):
    state=env.reset()
    done=False
    print("***Episode ",episode+1,"*****\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action=np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if(done):
            clear_output(wait=True)
            env.render()
            if(reward==1):
                print("***You reached the goal****")
                time.sleep(3)
            else:
                print("***You fell through the hole***")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state= new_state
        
env.close()
        
        

  (Up)
SFFF
FHFH
FFFH
HFFG
